# Generated by Django 4.2.7 on 2023-12-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tag_id", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="SideBar",
            new_name="Menu",
        ),
    ]
