# Generated by Django 4.2.7 on 2023-12-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_setting_rename_sidebar_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="icon",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="setting",
            name="icon",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
