# Generated by Django 4.2.7 on 2023-12-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0004_incident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="stage",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
