# Generated by Django 4.2.7 on 2023-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_alter_incident_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
