# Generated by Django 4.2.7 on 2023-12-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0006_alter_incident_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField()),
                ("time_stamp", models.DateField()),
                ("role", models.CharField(max_length=10)),
                ("content", models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name="incident",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
