# Generated by Django 5.0 on 2023-12-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_chatlog_alter_incident_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlog",
            name="time_stamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
