# Generated by Django 5.0 on 2023-12-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0008_alter_chatlog_time_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="time_stamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
